spring:
  boot:
    admin:
      client:
          url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"



spcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra

